name: Complex Arithmetic Operations

on:
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install

      - name: Perform Arithmetic Operations
        run: |
          echo "::set-env name=SUM::$(echo "10 + 5" | bc)"
          echo "::set-env name=DIFFERENCE::$(echo "10 - 5" | bc)"
          echo "::set-env name=PRODUCT::$(echo "10 * 5" | bc)"
          echo "::set-env name=QUOTIENT::$(echo "10 / 5" | bc)"

      - name: Display Results
        run: |
          echo "Sum: ${{ env.SUM }}"
          echo "Difference: ${{ env.DIFFERENCE }}"
          echo "Product: ${{ env.PRODUCT }}"
          echo "Quotient: ${{ env.QUOTIENT }}"
